### ISSUE TITLE
changing logfc.threshold

### ISSUE THREAD

**Issue by KarlKaise** [LingyiC/CASCC#1]
Hello, I am running into following issue while executing the code:

library(CASCC)
library(Seurat)
CASCC::checkDependencies()   

res <- CASCC::run.CASCC(normalized_matrix)

Warning message in asMethod(object):
“sparse->dense coercion: allocating vector of size 1.7 GiB”
Step 1: preparing the seed list... 
Warning message:
“The default method for RunUMAP has changed from calling Python UMAP via reticulate to the R-native UWOT using the cosine metric
To use Python UMAP via reticulate, set umap.method to 'umap-learn' and metric to 'correlation'
This message will be shown once per session”
For a more efficient implementation of the Wilcoxon Rank Sum Test,
(default method for FindMarkers) please install the limma package
--------------------------------------------
install.packages('BiocManager')
BiocManager::install('limma')
--------------------------------------------
After installation of limma, Seurat will automatically use the more 
efficient implementation (no further action necessary).
This message will be shown once per session

Warning message in FindMarkers.default(object = data.use, slot = data.slot, counts = counts, :
“No features pass min.diff.pct threshold; returning empty data.frame”
Warning message in FindMarkers.default(object = data.use, slot = data.slot, counts = counts, :
“No features pass logfc.threshold threshold; returning empty data.frame”
Warning message in FindMarkers.default(object = data.use, slot = data.slot, counts = counts, :
“No features pass logfc.threshold threshold; returning empty data.frame”
Warning message in FindMarkers.default(object = data.use, slot = data.slot, counts = counts, :
“No features pass logfc.threshold threshold; returning empty data.frame”
Warning message in FindMarkers.default(object = data.use, slot = data.slot, counts = counts, :
“No features pass logfc.threshold threshold; returning empty data.frame”
Warning message in FindMarkers.default(object = data.use, slot = data.slot, counts = counts, :
“No features pass logfc.threshold threshold; returning empty data.frame”
Warning message in FindMarkers.default(object = data.use, slot = data.slot, counts = counts, :
“No features pass logfc.threshold threshold; returning empty data.frame”
Warning message:
“package ‘dplyr’ was built under R version 4.3.3”

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

I would like to ask if I can manually change the thresholg for pass logfc.threshold as mentioned in supplementary material?

Thank you for any help.

**Comment by LingyiC** [comment]
Hi,

As described in the [CASCC supplementary material](https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/bioinformatics/PAP/10.1093_bioinformatics_btae283/1/btae283_supplementary_data.pdf?Expires=1717427195&Signature=C2tTpp6WBHzybpSahKqDd7F8PeEEut2q3LdpIq9TNxtwycUwa2~kSPmku4n0AekQz2EqxS8qvHgoVRiWDYzEk3jS6AYfMrDazT6zXaXxH5C~MVFra5pHUQxDzm3EMO45JLUAM4YZd2qteSYafAB0fMmObTHs7s1oWJ5lMQyktAmvrpXC8PiPRDKiKU7YZ0lCguUsobFnblOwWUZV1t3Pbi4VT8W8sQsrGgFznr5qPe7Z5~QBfQZhUisKd9pqZaNmkTdQ6GiFoBY9BaceX6s18LnUjFpyk5wwnbu1tfn7D6AtD7fwWJCAXo4x0ohoVT6pKsgGzm6VqqjmepqS5KPPCw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA), CASCC automatically adjusts parameters to identify markers. In most cases, CASCC can find sufficient markers without needing any manual adjustments.

> I would like to ask if I can manually change the thresholg for pass logfc.threshold as mentioned in supplementary material?

Yes, you can do that. In CASCC version 0.1.3 (please ensure you have reinstalled the updated version to access these parameters), parameters such as `logfc.threshold` and `min.pct`, which are linked to the Seurat FindAllMarkers function, can be modified to suit your specific requirements. Below is an example of how to manually set these parameters when running CASCC:

`res <- CASCC::run.CASCC(normalized_matrix, logfc.threshold = 0.25, min.pct = 0.25)`


Thanks,
Lingyi

**Comment by KarlKaise** [comment]
Thank you :)
